version: 2
jobs:
  deploy:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
      - run:
          name: heroku deploy
          command: |
            git subtree push  --prefix src/ https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master --force
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
